default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  username: weekly_workshop

development:
  <<: *default
  database: rails_and_ajax_development

test:
  <<: *default
  database: rails_and_ajax_test
